# Generated by Django 5.0.3 on 2024-04-03 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_expense", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="account", name="id",),
        migrations.AlterField(
            model_name="account",
            name="account_number",
            field=models.CharField(
                max_length=20,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="Account Number",
            ),
        ),
    ]
